fix form validation logic
vladilenm/vue-composition-demo pull request #1
Opened 2021-01-17 12:59 UTC by ximik753

This fixes a bug where the form is valid and the first field may not be valid.

2021-01-18 10:45 UTC, vladilenm requested changes

2021-01-18 10:45 UTC, vladilenm commented on src/use/form.js
> +      if (acc === false) {
лучше будет return acc && form[k].valid

а еще лучше вместе reduce использовать every

2021-01-18 18:14 UTC, ximik753 commented on src/use/form.js
> +      if (acc === false) {
Солидарен, every тут лучшее решение

2021-01-30 15:48 UTC, vladilenm approved these changes

2021-01-30 15:48 UTC, merged